import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logo from "../public/logo.svg";
import loginButton from "../public/loginButton.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cosmic Bots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image src={logo} alt="logo" className={styles.logo} />
        <Image src={loginButton} alt="logo" className={styles.loginButton} />
      </main>
    </div>
  );
}
